### ISSUE TITLE
Presets does not work? 

### ISSUE THREAD

**Issue by kyxap** [adam10603/AC-Advanced-Gamepad-Assist#30]
Hi there,

I've installed v1.4.1 and saw that there new cool feature with presets but seems like it does not work.

After selecting presets (e.g. stable) all buttons Load/Delete has `??` and not active/clickable.

![image](https://github.com/adam10603/AC-Advanced-Gamepad-Assist/assets/3080529/3b2f294f-00ed-4f6b-bb96-648f02bb37be)

Not sure if im doing something wrong.

 Thanks

**Comment by adam10603** [comment]
You're on an older CSP version, update to 0.2.0 or newer.
