### ISSUE TITLE
How is the gamepad rumble effect accessed in the lower layers?

### ISSUE THREAD

**Issue by topas-rec** [adam10603/AC-Advanced-Gamepad-Assist#40]
Hello,

thanks a lot for this mod.

I use it on Linux together with an Xbox one controller and the trigger force feedback does not work.
I wanted to investigate here a little and maybe report a bug at wine, but I can't find how the lower layer is accessed or which the lower layer for force feedback or the gamepad more generally is.
This would be helpful for the issue report or maybe I can do something myself here.

I tried to find out myself, but I am stuck at one point.
I found

https://github.com/adam10603/AC-Advanced-Gamepad-Assist/blob/79592fcf6c6a26f66bd85e053785755daf8bbacc/Advanced%20Gamepad%20Assist/extension/lua/joypad-assist/Advanced%20Gamepad%20Assist/extras.lua#L252

and I also found that `ac` is a namespace from Lua SDK in CSP:
https://github.com/ac-custom-shaders-patch/acc-lua-sdk/blob/d1a7464ec7354eaebef5ff9c91409e4232bc6bbf/common/common.d.lua#L17

I cannot find the function in the lua SDK on github.
I can find a declaration in the code that is distributed, but not the definition of it.

Do you know where the function is defined? Is it public code?
If not do you know the interface to the operating system?

I could also ask the CSP developer, but I wanted to start here.

Best wishes.

**Comment by adam10603** [comment]
Sorry, I don't check issues often.
That code isn't open source as far as I know, all there is is the declaration. You'd have to take this up with the CSP devs.
But I do know that on Windows you have to disable Steam input because for some reason it doesn't allow the vibrations to work. Not sure if that applies on Linux too but maybe it's worth a look.

**Comment by topas-rec** [comment]
> Sorry, I don't check issues often.

No problem, thanks for providing feedback.
